// app/services/meal-planner/mealTemplates.ts
import { MealTemplate } from '../../../types/meal-planner.types';

export const BREAKFAST_TEMPLATES: MealTemplate[] = [
  {
    id: 'b1',
    name: 'Oatmeal with Fruits',
    type: 'breakfast',
    foods: ['Oats', 'Banana', 'Honey', 'Milk'],
    calories: 350,
    protein: 12,
    carbs: 45,
    fat: 8,
    preparationTime: 10,
    recipe: 'Mix oats with milk, add sliced banana and honey.',
    icon: '🥣',
  },
  {
    id: 'b2',
    name: 'Egg & Toast',
    type: 'breakfast',
    foods: ['Eggs', 'Whole Grain Bread', 'Butter'],
    calories: 320,
    protein: 18,
    carbs: 25,
    fat: 15,
    preparationTime: 10,
    recipe: 'Fry eggs, toast bread, add butter.',
    icon: '🍳',
  },
  {
    id: 'b3',
    name: 'Fruit Smoothie',
    type: 'breakfast',
    foods: ['Banana', 'Milk', 'Strawberries', 'Yogurt'],
    calories: 280,
    protein: 10,
    carbs: 40,
    fat: 5,
    preparationTime: 5,
    recipe: 'Blend all ingredients together.',
    icon: '🥤',
  },
  {
    id: 'b4',
    name: 'Greek Yogurt with Granola',
    type: 'breakfast',
    foods: ['Greek Yogurt', 'Granola', 'Honey'],
    calories: 300,
    protein: 20,
    carbs: 30,
    fat: 10,
    preparationTime: 5,
    recipe: 'Mix yogurt with granola and honey.',
    icon: '🥛',
  },
  {
    id: 'b5',
    name: 'Avocado Toast',
    type: 'breakfast',
    foods: ['Avocado', 'Toast', 'Egg'],
    calories: 340,
    protein: 14,
    carbs: 28,
    fat: 18,
    preparationTime: 10,
    recipe: 'Mash avocado on toast, top with egg.',
    icon: '🥑',
  },
];

export const LUNCH_TEMPLATES: MealTemplate[] = [
  {
    id: 'l1',
    name: 'Grilled Chicken Salad',
    type: 'lunch',
    foods: ['Chicken Breast', 'Lettuce', 'Olive Oil', 'Tomatoes'],
    calories: 400,
    protein: 35,
    carbs: 20,
    fat: 18,
    preparationTime: 20,
    recipe: 'Grill chicken, mix with vegetables.',
    icon: '🥗',
  },
  {
    id: 'l2',
    name: 'Vegetable Rice Bowl',
    type: 'lunch',
    foods: ['Rice', 'Mixed Vegetables', 'Soy Sauce'],
    calories: 450,
    protein: 12,
    carbs: 60,
    fat: 15,
    preparationTime: 25,
    recipe: 'Cook rice, stir-fry vegetables, mix together.',
    icon: '🍚',
  },
  {
    id: 'l3',
    name: 'Fish & Chips',
    type: 'lunch',
    foods: ['Fish', 'Potatoes', 'Oil'],
    calories: 550,
    protein: 30,
    carbs: 45,
    fat: 25,
    preparationTime: 30,
    recipe: 'Fry fish and potatoes.',
    icon: '🐟',
  },
  {
    id: 'l4',
    name: 'Quinoa Bowl',
    type: 'lunch',
    foods: ['Quinoa', 'Chickpeas', 'Vegetables'],
    calories: 380,
    protein: 15,
    carbs: 45,
    fat: 12,
    preparationTime: 20,
    recipe: 'Cook quinoa, mix with chickpeas and vegetables.',
    icon: '🥙',
  },
];

export const DINNER_TEMPLATES: MealTemplate[] = [
  {
    id: 'd1',
    name: 'Spaghetti Bolognese',
    type: 'dinner',
    foods: ['Pasta', 'Minced Meat', 'Tomato Sauce'],
    calories: 500,
    protein: 25,
    carbs: 55,
    fat: 20,
    preparationTime: 35,
    recipe: 'Cook pasta, make meat sauce, combine.',
    icon: '🍝',
  },
  {
    id: 'd2',
    name: 'Grilled Salmon with Vegetables',
    type: 'dinner',
    foods: ['Salmon', 'Broccoli', 'Olive Oil'],
    calories: 480,
    protein: 40,
    carbs: 15,
    fat: 25,
    preparationTime: 25,
    recipe: 'Grill salmon, steam vegetables.',
    icon: '🐟',
  },
  {
    id: 'd3',
    name: 'Chicken Curry with Rice',
    type: 'dinner',
    foods: ['Chicken', 'Rice', 'Curry Powder'],
    calories: 520,
    protein: 30,
    carbs: 50,
    fat: 20,
    preparationTime: 40,
    recipe: 'Cook chicken curry, serve with rice.',
    icon: '🍛',
  },
  {
    id: 'd4',
    name: 'Vegetable Stir Fry',
    type: 'dinner',
    foods: ['Mixed Vegetables', 'Tofu', 'Soy Sauce'],
    calories: 350,
    protein: 18,
    carbs: 30,
    fat: 15,
    preparationTime: 20,
    recipe: 'Stir-fry vegetables and tofu.',
    icon: '🥬',
  },
];

export const SNACK_TEMPLATES: MealTemplate[] = [
  {
    id: 's1',
    name: 'Apple with Peanut Butter',
    type: 'snack',
    foods: ['Apple', 'Peanut Butter'],
    calories: 200,
    protein: 5,
    carbs: 25,
    fat: 10,
    preparationTime: 5,
    recipe: 'Slice apple, spread peanut butter.',
    icon: '🍎',
  },
  {
    id: 's2',
    name: 'Trail Mix',
    type: 'snack',
    foods: ['Nuts', 'Dried Fruits'],
    calories: 180,
    protein: 6,
    carbs: 15,
    fat: 12,
    preparationTime: 2,
    recipe: 'Mix nuts and dried fruits.',
    icon: '🥜',
  },
  {
    id: 's3',
    name: 'Greek Yogurt',
    type: 'snack',
    foods: ['Greek Yogurt'],
    calories: 150,
    protein: 15,
    carbs: 8,
    fat: 5,
    preparationTime: 2,
    recipe: 'Serve chilled.',
    icon: '🥛',
  },
  {
    id: 's4',
    name: 'Hummus with Carrots',
    type: 'snack',
    foods: ['Hummus', 'Carrots'],
    calories: 160,
    protein: 5,
    carbs: 18,
    fat: 8,
    preparationTime: 5,
    recipe: 'Dip carrots in hummus.',
    icon: '🥕',
  },
];

export const ALL_TEMPLATES = {
  breakfast: BREAKFAST_TEMPLATES,
  lunch: LUNCH_TEMPLATES,
  dinner: DINNER_TEMPLATES,
  snack: SNACK_TEMPLATES,
};

export const getTemplatesByType = (type: 'breakfast' | 'lunch' | 'dinner' | 'snack'): MealTemplate[] => {
  return ALL_TEMPLATES[type] || [];
};

export const getRandomMeal = (type: 'breakfast' | 'lunch' | 'dinner' | 'snack'): MealTemplate | null => {
  const templates = getTemplatesByType(type);
  if (templates.length === 0) return null;
  const randomIndex = Math.floor(Math.random() * templates.length);
  return templates[randomIndex];
};