import { Product, Category } from '../types/marketplace.types';

export const SAMPLE_PRODUCTS: Product[] = [
  // Vegetables
  {
    id: 'p1',
    name: 'Organic Carrots',
    nameSi: 'කාබනික කැරට්',
    description: 'Fresh organic carrots from Nuwara Eliya farms. Rich in Vitamin A and antioxidants.',
    category: 'Vegetables',
    price: 350,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
    nutrition: { calories: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8 },
    isOrganic: true,
    isLocal: true,
    isSeasonal: true,
    seller: { name: 'Green Valley Farms', location: 'Nuwara Eliya', rating: 4.8 },
    available: true,
    stock: 50,
    rating: 4.9,
    reviews: 120,
    tags: ['organic', 'local', 'seasonal'],
  },
  {
    id: 'p2',
    name: 'Fresh Tomatoes',
    nameSi: 'නැවුම් තක්කාලි',
    description: 'Juicy tomatoes from Dambulla. Perfect for salads and curries.',
    category: 'Vegetables',
    price: 250,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400',
    nutrition: { calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2 },
    isOrganic: false,
    isLocal: true,
    isSeasonal: true,
    seller: { name: 'Dambulla Fresh', location: 'Dambulla', rating: 4.6 },
    available: true,
    stock: 80,
    rating: 4.7,
    reviews: 95,
    tags: ['local', 'seasonal'],
  },
  {
    id: 'p3',
    name: 'Green Beans',
    nameSi: 'බෝංචි',
    description: 'Fresh green beans from Kandy. Rich in fiber and vitamins.',
    category: 'Vegetables',
    price: 400,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1515453294519-7b6af2f79c15?w=400',
    nutrition: { calories: 31, protein: 1.8, carbs: 7, fat: 0.2, fiber: 3.4 },
    isOrganic: true,
    isLocal: true,
    isSeasonal: false,
    seller: { name: 'Kandy Organic', location: 'Kandy', rating: 4.7 },
    available: true,
    stock: 30,
    rating: 4.5,
    reviews: 68,
    tags: ['organic', 'local'],
  },

  // Fruits
  {
    id: 'p4',
    name: 'Organic Mangoes',
    nameSi: 'කාබනික අඹ',
    description: 'Sweet organic mangoes from Anuradhapura. King of fruits!',
    category: 'Fruits',
    price: 500,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400',
    nutrition: { calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6 },
    isOrganic: true,
    isLocal: true,
    isSeasonal: true,
    seller: { name: 'Anuradhapura Farms', location: 'Anuradhapura', rating: 4.9 },
    available: true,
    stock: 40,
    rating: 4.9,
    reviews: 150,
    tags: ['organic', 'local', 'seasonal', 'fruit'],
  },
  {
    id: 'p5',
    name: 'Rambutan',
    nameSi: 'රම්බුටන්',
    description: 'Sweet juicy rambutan from Matara. Tropical delight!',
    category: 'Fruits',
    price: 450,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f1e5?w=400',
    nutrition: { calories: 82, protein: 1, carbs: 20, fat: 0.3, fiber: 2.9 },
    isOrganic: false,
    isLocal: true,
    isSeasonal: true,
    seller: { name: 'Matara Fruits', location: 'Matara', rating: 4.5 },
    available: true,
    stock: 60,
    rating: 4.6,
    reviews: 82,
    tags: ['local', 'seasonal', 'fruit'],
  },

  // Grains
  {
    id: 'p6',
    name: 'Organic Brown Rice',
    nameSi: 'කාබනික රතු හාල්',
    description: 'Healthy organic brown rice from Polonnaruwa. Rich in fiber and nutrients.',
    category: 'Grains',
    price: 380,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e8e4?w=400',
    nutrition: { calories: 370, protein: 7.5, carbs: 77, fat: 2.5, fiber: 3.5 },
    isOrganic: true,
    isLocal: true,
    isSeasonal: false,
    seller: { name: 'Polonnaruwa Rice', location: 'Polonnaruwa', rating: 4.8 },
    available: true,
    stock: 100,
    rating: 4.8,
    reviews: 200,
    tags: ['organic', 'local', 'grain'],
  },
  {
    id: 'p7',
    name: 'Organic Red Lentils',
    nameSi: 'කාබනික රතු පරිප්පු',
    description: 'High protein organic red lentils from Kurunegala.',
    category: 'Grains',
    price: 420,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e8e4?w=400',
    nutrition: { calories: 350, protein: 25, carbs: 60, fat: 1.5, fiber: 8 },
    isOrganic: true,
    isLocal: true,
    isSeasonal: false,
    seller: { name: 'Kurunegala Grains', location: 'Kurunegala', rating: 4.4 },
    available: true,
    stock: 70,
    rating: 4.4,
    reviews: 55,
    tags: ['organic', 'local', 'grain', 'protein'],
  },

  // Dairy
  {
    id: 'p8',
    name: 'Fresh Curd',
    nameSi: 'නැවුම් මුදවපු කිරි',
    description: 'Traditional fresh curd from Galle. Creamy and delicious.',
    category: 'Dairy',
    price: 250,
    unit: 'piece',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    nutrition: { calories: 120, protein: 5, carbs: 4, fat: 8, fiber: 0 },
    isOrganic: false,
    isLocal: true,
    isSeasonal: false,
    seller: { name: 'Galle Dairy', location: 'Galle', rating: 4.7 },
    available: true,
    stock: 25,
    rating: 4.7,
    reviews: 75,
    tags: ['local', 'dairy'],
  },
  {
    id: 'p9',
    name: 'Organic Eggs',
    nameSi: 'කාබනික බිත්තර',
    description: 'Free range organic eggs from Matale farms.',
    category: 'Dairy',
    price: 300,
    unit: 'dozen',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400',
    nutrition: { calories: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0 },
    isOrganic: true,
    isLocal: true,
    isSeasonal: false,
    seller: { name: 'Matale Organic', location: 'Matale', rating: 4.6 },
    available: true,
    stock: 15,
    rating: 4.6,
    reviews: 90,
    tags: ['organic', 'local', 'dairy'],
  },

  // Spices
  {
    id: 'p10',
    name: 'Pure Ceylon Cinnamon',
    nameSi: 'නිවැරදි කුරුඳු',
    description: 'True Ceylon cinnamon from the spice gardens of Matale.',
    category: 'Spices',
    price: 600,
    unit: '100g',
    image: 'https://images.unsplash.com/photo-1534432586043-ead5b7f2c67a?w=400',
    nutrition: { calories: 247, protein: 4, carbs: 80, fat: 1.2, fiber: 53 },
    isOrganic: true,
    isLocal: true,
    isSeasonal: false,
    seller: { name: 'Spice Gardens', location: 'Matale', rating: 4.9 },
    available: true,
    stock: 45,
    rating: 4.9,
    reviews: 180,
    tags: ['organic', 'local', 'spice', 'premium'],
  },
  {
    id: 'p11',
    name: 'Organic Turmeric',
    nameSi: 'කාබනික කහ',
    description: 'Fresh organic turmeric from Kegalle. Rich in curcumin.',
    category: 'Spices',
    price: 350,
    unit: '100g',
    image: 'https://images.unsplash.com/photo-1534432586043-ead5b7f2c67a?w=400',
    nutrition: { calories: 354, protein: 8, carbs: 65, fat: 10, fiber: 21 },
    isOrganic: true,
    isLocal: true,
    isSeasonal: true,
    seller: { name: 'Kegalle Organic', location: 'Kegalle', rating: 4.5 },
    available: true,
    stock: 30,
    rating: 4.5,
    reviews: 65,
    tags: ['organic', 'local', 'spice'],
  },
];

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All', nameSi: 'සියල්ල', icon: 'grid', count: SAMPLE_PRODUCTS.length },
  { id: 'vegetables', name: 'Vegetables', nameSi: 'එළවළු', icon: 'leaf', count: SAMPLE_PRODUCTS.filter(p => p.category === 'Vegetables').length },
  { id: 'fruits', name: 'Fruits', nameSi: 'පලතුරු', icon: 'apple', count: SAMPLE_PRODUCTS.filter(p => p.category === 'Fruits').length },
  { id: 'grains', name: 'Grains', nameSi: 'ධාන්‍ය', icon: 'wheat', count: SAMPLE_PRODUCTS.filter(p => p.category === 'Grains').length },
  { id: 'dairy', name: 'Dairy', nameSi: 'කිරි නිෂ්පාදන', icon: 'cup', count: SAMPLE_PRODUCTS.filter(p => p.category === 'Dairy').length },
  { id: 'spices', name: 'Spices', nameSi: 'කුළුබඩු', icon: 'flask', count: SAMPLE_PRODUCTS.filter(p => p.category === 'Spices').length },
];

export const defaultFilters = {
  category: 'all',
  priceRange: { min: 0, max: 1000 },
  isOrganic: false,
  isLocal: false,
  isSeasonal: false,
  searchQuery: '',
};